.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SHELR" "1" "April 2012" "" ""
.
.SH "NAME"
\fBshelr\fR \- screencasting for shell ninjas
.
.SH "DESCRIPTION"
\fBShelr\fR records terminal output and can replay it\.
.
.P
Also you can shere Your records at http://shelr\.tv/ or other services\.
.
.SH "SYNOPSIS"
\fBshelr\fR command [id]
.
.SH "COMMANDS"
.
.TP
\fBrecord\fR
Will record your terminal unless you type \fBexit\fR or Ctrl+D and store it to $HOME/\.local/share/shelr/
.
.TP
\fBstop\fR
Will stop recording\. You can just type exit in shell or Ctrl+D\. Record will be stored to $HOME/\.local/share/shelr/
.
.TP
\fBlist\fR
lists all your shellcasts\.
.
.TP
\fBplay\fR
plays local or remote shellcast\.
.
.TP
\fBpush\fR
publish your shellcast
.
.TP
\fBdump\fR
dump shellcast as json to current directory\.
.
.SH "EXAMPLES"
Record your shellcast:
.
.IP "" 4
.
.nf

$ shelr record
\.\.\. do something \.\.\.
$ exit
.
.fi
.
.IP "" 0
.
.P
List recorded shellcasts:
.
.IP "" 4
.
.nf

$ shelr list
.
.fi
.
.IP "" 0
.
.P
Play local shellcast:
.
.IP "" 4
.
.nf

$ shelr play 1293702847  # play your own local record
$ shelr play record\.json # created with shelr dump
$ shelr play last        # will play most recent local record
.
.fi
.
.IP "" 0
.
.P
Play remote shellcast:
.
.IP "" 4
.
.nf

$ shelr play http://shelr\.tv/records/4d1f7c3890820d6144000002\.json
.
.fi
.
.IP "" 0
.
.P
Publish your shellcast:
.
.IP "" 4
.
.nf

$ shelr push 1293702847
$ shelr push last # will push most recent local record
.
.fi
.
.IP "" 0
.
.P
Setup recording backend:
.
.IP "" 4
.
.nf

$ shelr backend script
$ shelr backend ttyrec
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBWindows\fR heh\.
.
.SH "COPYRIGHT"
(C) 2010, 2011, 2012 Antono Vasiljev \fIself@antono\.info\fR
.
.P
Licensed under GPLv3+
.
.SH "SEE ALSO"
script(1), scriptreplay(1), ttyrec(1), ttyplay(1)
